### ISSUE TITLE
Doesn't display any linting error on minimap after upgrading to linter 2.0

### ISSUE THREAD

**Issue by vanduynslagerp** [AtomLinter/atom-minimap-linter#11]
The minimap menu still allow to select/unselect linter, but the error/warning are not highlighted on the minimap.

![2017-03-14_15-05-16](https://cloud.githubusercontent.com/assets/3250552/23918173/433d0d7c-08c8-11e7-86b7-a5d409c92f3c.png)

Using:
- minimap 4.26.8
- minimap-linter 1.6.0
- linter 2.1.0
- linter-ui-default 1.1.0

Let me know if you need additional informations

**Comment by Arcanemagus** [comment]
Hmmmm, this is odd, I've been using the v2 branch for quite a while now and it's been working for me.

**Comment by Arcanemagus** [comment]
Scratch that, guess it isn't working 😛.

**Comment by steelbrain** [comment]
This package used to intercept all the highlights on the editor to know where linter has painted, as of v2, this package can directly register itself as a UI provider and be future-safe

**Comment by Arcanemagus** [comment]
I'm looking into getting this working again, looks like this project has needed some love for a while now.

**Comment by JLCCI** [comment]
+1

**Comment by vanduynslagerp** [comment]
Hello, do you have an update on this issue, by any chance ?
The minimap-linter package is not usable anymore...
Thanks !

**Comment by Arcanemagus** [comment]
Fixed in #12, will be pushing out v2.0.0 with that shortly!

**Comment by vanduynslagerp** [comment]
Awesome ! Thanks a lot !
