### ISSUE TITLE
Multiple panes do not have consistent highlights on minimap

### ISSUE THREAD

**Issue by mehcode** [AtomLinter/atom-minimap-linter#16]
![screen shot 2017-07-13 at 2 20 06 am](https://user-images.githubusercontent.com/753919/28159473-e8de31d6-6771-11e7-9128-f5671919971a.png)

Reproduce:
 1. Open a file. Get some errors going. See those minimap-linter highlights.
 2. Split the file into a new pane. Notice the minimap-linter highlights do not get applied to the new pane.

**Comment by Arcanemagus** [comment]
Ooo, very interesting bug, looks like even when a new lint is triggered the old messages aren't shown since this only uses the `patch` messages for updates.
