### ISSUE TITLE
Feature request: add option to disable "linter infos" on minimap

### ISSUE THREAD

**Issue by Dylan-Brotherston** [AtomLinter/atom-minimap-linter#21]
Linters like Pylint produce "linter infos" if your code doesn't follow the style guide, and this can really clog up the minimap.

A way to disable "linter infos" showing would really help.

**Comment by Arcanemagus** [comment]
Minimap itself allows you to toggle the display of any plugin by clicking the "gear" and clicking the name of the plugin.

**Comment by Dylan-Brotherston** [comment]
True, but i was talking about toggling only "linter infos" not "linter warnings" or "linter errors".
