### ISSUE TITLE
atom-ide-ui changed message structure

### ISSUE THREAD

**Issue by jacobmischka** [AtomLinter/atom-minimap-linter#29]
It would be great if this package also worked with atom-ide-ui. I'm under the impression that the diagnostics created by ide-ui are essentially the same as the linter errors under the hood, so hopefully this won't be too difficult.

Thank you for all your work!

**Comment by Arcanemagus** [comment]
Actually the part that this package interacts with is entirely different, however it was already implemented in #23 and released in v2.1.0. 😉

**Comment by jacobmischka** [comment]
Hm, I have 2.1.1 and I don't seem to be getting anything.

![screenshot from 2017-10-24 08-19-44](https://user-images.githubusercontent.com/3939997/31955402-e2f50a00-b8ad-11e7-8811-6c2fbb437c99.png)

**Comment by jacobmischka** [comment]
Regardless, thanks for already adding it! I'll try to dig a little deeper and report back.

**Comment by Arcanemagus** [comment]
Hmmm, maybe they broke something? There have been two releases of `atom-ide-ui` since that was written.

**Comment by Arcanemagus** [comment]
Can confirm it's no longer working...

**Comment by Arcanemagus** [comment]
It looks like they changed the structure of the messages without changing the version of the service 😞.

**Comment by jacobmischka** [comment]
Thanks a bunch for the quick work!

**Comment by Arcanemagus** [comment]
Fix published in v2.1.2, thanks for reporting it!

**Comment by jacobmischka** [comment]
Sorry, I definitely see that you published a release to github but I can't seem to find v2.1.2 on the apm registry.

`apm upgrade` isn't returning anything and `apm install minimap-linter` gives me v2.1.1 still. I'm not very familiar with apm publishing so I'm not entirely sure why that might be happening.

Thanks again!

**Comment by Arcanemagus** [comment]
> Sorry, I definitely see that you published a release to github but I can't seem to find v2.1.2 on the apm registry.

Whoops, re-installed the computer last week and apparently the prompt has been sitting waiting to be authorized to `apm`! Thanks for prompting!
