### ISSUE TITLE
Feature request: add minimap marker option of "gutter"

### ISSUE THREAD

**Issue by jolsenmultiad** [AtomLinter/atom-minimap-linter#9]
Thanks for a nice minimap plugin!

If possible, please add another marker type of "gutter" (not sure what a good name would be) that would only highlight the beginning of a line or block, and not the entire line. This would be similar in appearance (just smaller) to the linter bullet marker that appears in the gutter of the main editor pane.

**Comment by nesukun** [comment]
I have to check if minimap supports such kind of marker. If it does, sure I'll add support for that. Thanks for the suggestion!

**Comment by nesukun** [comment]
Added in lastest version
